import type { Category } from "@/types/category";
import { CategoryId } from "@/enums/category-id";

export const CATEGORIES: Category[] = [
  {
    id: CategoryId.Currency,
    name: "Currency",
    tagline: "Every Currency on Earth. And Off It.",
    description: "Convert between 160+ fiat currencies, 80+ cryptocurrencies, and 20+ stock market tickers. Six independent rate providers cross-verify every exchange rate for unmatched accuracy.",
    unitCount: "260+",
    gradientStart: "#66BB6A",
    gradientEnd: "#2E7D32",
    iconPath: "M12 8c-1.657 0-3 .895-3 2s1.343 2 3 2 3 .895 3 2-1.343 2-3 2m0-8c1.11 0 2.08.402 2.599 1M12 8V7m0 1v8m0 0v1m0-1c-1.11 0-2.08-.402-2.599-1M21 12a9 9 0 11-18 0 9 9 0 0118 0z",
    subcategories: [
      { name: "Fiat Currencies", examples: ["USD", "EUR", "GBP", "JPY"] },
      { name: "Cryptocurrencies", examples: ["BTC", "ETH", "SOL", "DOGE"] },
      { name: "Stock Market", examples: ["AAPL", "GOOGL", "TSLA", "AMZN"] },
    ],
  },
  {
    id: CategoryId.Distance,
    name: "Distance",
    tagline: "From Angstroms to Light Years.",
    description: "144 distance and length units spanning metric, imperial, maritime, astronomical, and 12+ historic measurement systems from around the globe.",
    unitCount: "144",
    gradientStart: "#42A5F5",
    gradientEnd: "#1565C0",
    iconPath: "M13 7h8m0 0v8m0-8l-8 8-4-4-6 6",
    subcategories: [
      { name: "Metric" },
      { name: "Imperial" },
      { name: "Maritime" },
      { name: "Historical" },
      { name: "Asian" },
      { name: "Indian" },
      { name: "Astronomical" },
      { name: "Typography" },
      { name: "Southeast Asian" },
      { name: "Islamic/Arabic" },
      { name: "Persian" },
      { name: "Biblical" },
      { name: "African" },
      { name: "Celtic/Nordic" },
      { name: "Ottoman" },
      { name: "Hindu/Vedic" },
      { name: "Polynesian" },
    ],
  },
  {
    id: CategoryId.Apparel,
    name: "Apparel",
    tagline: "Your Size. Any Country.",
    description: "Convert apparel sizes across 18+ countries including shoes, clothing, pants, and rings. Never order the wrong size again when shopping internationally.",
    unitCount: "18+ countries",
    gradientStart: "#AB47BC",
    gradientEnd: "#6A1B9A",
    iconPath: "M16 11V7a4 4 0 00-8 0v4M5 9h14l1 12H4L5 9z",
    subcategories: [
      { name: "Men's Shoes" },
      { name: "Women's Shoes" },
      { name: "Children's Shoes" },
      { name: "Clothing" },
      { name: "Pants" },
      { name: "Rings" },
    ],
  },
  {
    id: CategoryId.Storage,
    name: "Data Storage",
    tagline: "Bits to Blu-rays. Every Unit Counted.",
    description: "60 data storage and transfer units from individual bits to structural media formats. Covers SI, IEC binary, and real-world storage media references.",
    unitCount: "60",
    gradientStart: "#26C6DA",
    gradientEnd: "#00838F",
    iconPath: "M4 7v10c0 2.21 3.582 4 8 4s8-1.79 8-4V7M4 7c0 2.21 3.582 4 8 4s8-1.79 8-4M4 7c0-2.21 3.582-4 8-4s8 1.79 8 4m0 5c0 2.21-3.582 4-8 4s-8-1.79-8-4",
    subcategories: [
      { name: "Bit Units" },
      { name: "Byte Units" },
      { name: "Binary (IEC) Units" },
      { name: "SI Extensions" },
      { name: "Structural Units" },
      { name: "Storage Media" },
    ],
  },
  {
    id: CategoryId.Mass,
    name: "Weight",
    tagline: "Atoms to Earth Masses.",
    description: "122 mass and weight units spanning metric, imperial, precious metals, apothecary, and 14+ traditional measurement systems from civilizations worldwide.",
    unitCount: "122",
    gradientStart: "#FFA726",
    gradientEnd: "#E65100",
    iconPath: "M3 6l3 1m0 0l-3 9a5.002 5.002 0 006.001 0M6 7l3 9M6 7l6-2m6 2l3-1m-3 1l3 9a5.002 5.002 0 006.001 0M18 7l3 9m-3-9l-6-2m0-2v2m0 16V5m0 16H9m3 0h3",
    subcategories: [
      { name: "Metric" },
      { name: "Imperial" },
      { name: "Precious Metals" },
      { name: "Apothecary" },
      { name: "Asian" },
      { name: "Indian" },
      { name: "Scientific" },
      { name: "European Historical" },
      { name: "Middle Eastern" },
      { name: "Southeast Asian" },
      { name: "Latin American" },
      { name: "Islamic/Arabic" },
      { name: "Hindu/Vedic" },
      { name: "Biblical" },
      { name: "Persian" },
      { name: "African" },
      { name: "Ottoman" },
      { name: "Polynesian" },
    ],
  },
];
