import type { Competitor } from "@/types/competitor";
import { BRAND_NAME } from "@/constants/brand";

export const COMPARISON_FEATURES = [
  "Multi-target conversion",
  "Expression evaluation in input",
  "Bargain mode",
  "Apparel & ring size conversion",
  "Location-based currency defaults",
  "Multiple exchange rate providers",
  "Offline mode with cached rates",
  "Real-time crypto & stock tickers",
  "Conversion history & favorites",
  "Built-in bug report with attachments",
  "Cross-platform availability",
  "Theme options",
] as const;

export const COMPETITORS: Competitor[] = [
  {
    name: BRAND_NAME,
    features: {
      "Multi-target conversion": "Up to 6 targets",
      "Expression evaluation in input": true,
      "Bargain mode": true,
      "Apparel & ring size conversion": true,
      "Location-based currency defaults": true,
      "Multiple exchange rate providers": "11 providers",
      "Offline mode with cached rates": true,
      "Real-time crypto & stock tickers": true,
      "Conversion history & favorites": true,
      "Built-in bug report with attachments": true,
      "Cross-platform availability": "iOS, Android",
      "Theme options": "4 modes",
    },
  },
  {
    name: "XE Currency",
    features: {
      "Multi-target conversion": "Limited",
      "Expression evaluation in input": false,
      "Bargain mode": false,
      "Apparel & ring size conversion": false,
      "Location-based currency defaults": true,
      "Multiple exchange rate providers": "1",
      "Offline mode with cached rates": true,
      "Real-time crypto & stock tickers": false,
      "Conversion history & favorites": false,
      "Built-in bug report with attachments": false,
      "Cross-platform availability": "iOS, Android, Web",
      "Theme options": "2 modes",
    },
  },
  {
    name: "OANDA Converter",
    features: {
      "Multi-target conversion": false,
      "Expression evaluation in input": false,
      "Bargain mode": false,
      "Apparel & ring size conversion": false,
      "Location-based currency defaults": true,
      "Multiple exchange rate providers": "1",
      "Offline mode with cached rates": false,
      "Real-time crypto & stock tickers": false,
      "Conversion history & favorites": true,
      "Built-in bug report with attachments": false,
      "Cross-platform availability": "iOS, Android, Web",
      "Theme options": "1",
    },
  },
  {
    name: "ConvertPad",
    features: {
      "Multi-target conversion": false,
      "Expression evaluation in input": true,
      "Bargain mode": false,
      "Apparel & ring size conversion": false,
      "Location-based currency defaults": false,
      "Multiple exchange rate providers": "1",
      "Offline mode with cached rates": true,
      "Real-time crypto & stock tickers": false,
      "Conversion history & favorites": true,
      "Built-in bug report with attachments": false,
      "Cross-platform availability": "Android only",
      "Theme options": "2 modes",
    },
  },
  {
    name: "Google Unit Converter",
    features: {
      "Multi-target conversion": false,
      "Expression evaluation in input": false,
      "Bargain mode": false,
      "Apparel & ring size conversion": false,
      "Location-based currency defaults": false,
      "Multiple exchange rate providers": "1",
      "Offline mode with cached rates": false,
      "Real-time crypto & stock tickers": false,
      "Conversion history & favorites": false,
      "Built-in bug report with attachments": false,
      "Cross-platform availability": "Web only",
      "Theme options": "1",
    },
  },
];
