export const CAROUSEL_INTERVAL = {
  HERO_MS: 4000,
  FEATURES_MS: 5000,
  CATEGORIES_MS: 5000,
  COMPARE_MS: 6000,
  GUIDE_MS: 6000,
  SHOWCASE_MS: 6000,
} as const;

export const TRANSITION_DURATION = {
  THEME_CYCLE_MS: 300,
  SUBSCRIBE_RESET_MS: 3000,
} as const;

export const SCROLL_THRESHOLD = {
  HEADER_CAPSULE_PX: 40,
  DOWNLOAD_OBSERVER_THRESHOLD: 0.08,
} as const;

export const ANIMATION_DELAY = {
  SHOWCASE_STAGGER_MS: 60,
  GUIDE_STEP_STAGGER_MS: 80,
  GUIDE_TAG_STAGGER_MS: 60,
  GUIDE_TAG_BASE_MS: 200,
  COMPARE_CARD_STAGGER_MS: 60,
  FOOTER_TICKER_STAGGER_MS: 100,
  HERO_TARGET_STAGGER_S: 0.08,
  HERO_STAT_CHIP_1_S: "0.2s",
  HERO_STAT_CHIP_2_S: "0.35s",
  HERO_STAT_CHIP_3_S: "0.5s",
  SUBCATEGORY_STAGGER_S: 0.05,
  FEATURES_CHIP_STAGGER_MS: 60,
  FEATURES_CHIP_BASE_MS: 120,
  CATEGORIES_CHIP_STAGGER_MS: 40,
} as const;
